// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/task_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/task_repo.go -destination=internal/mock/task_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "notification-service/internal/model"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockITaskRepo is a mock of ITaskRepo interface.
type MockITaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockITaskRepoMockRecorder
	isgomock struct{}
}

// MockITaskRepoMockRecorder is the mock recorder for MockITaskRepo.
type MockITaskRepoMockRecorder struct {
	mock *MockITaskRepo
}

// NewMockITaskRepo creates a new mock instance.
func NewMockITaskRepo(ctrl *gomock.Controller) *MockITaskRepo {
	mock := &MockITaskRepo{ctrl: ctrl}
	mock.recorder = &MockITaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITaskRepo) EXPECT() *MockITaskRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockITaskRepo) Create(ctx context.Context, task *model.NotificationTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockITaskRepoMockRecorder) Create(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockITaskRepo)(nil).Create), ctx, task)
}

// FetchPending mocks base method.
func (m *MockITaskRepo) FetchPending(ctx context.Context, limit int) ([]model.NotificationTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPending", ctx, limit)
	ret0, _ := ret[0].([]model.NotificationTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPending indicates an expected call of FetchPending.
func (mr *MockITaskRepoMockRecorder) FetchPending(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPending", reflect.TypeOf((*MockITaskRepo)(nil).FetchPending), ctx, limit)
}

// GetByID mocks base method.
func (m *MockITaskRepo) GetByID(ctx context.Context, id int64) (*model.NotificationTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.NotificationTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockITaskRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockITaskRepo)(nil).GetByID), ctx, id)
}

// ListByStatus mocks base method.
func (m *MockITaskRepo) ListByStatus(ctx context.Context, status string, page, pageSize int) ([]model.NotificationTask, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStatus", ctx, status, page, pageSize)
	ret0, _ := ret[0].([]model.NotificationTask)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByStatus indicates an expected call of ListByStatus.
func (mr *MockITaskRepoMockRecorder) ListByStatus(ctx, status, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStatus", reflect.TypeOf((*MockITaskRepo)(nil).ListByStatus), ctx, status, page, pageSize)
}

// LockForDelivery mocks base method.
func (m *MockITaskRepo) LockForDelivery(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockForDelivery", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockForDelivery indicates an expected call of LockForDelivery.
func (mr *MockITaskRepoMockRecorder) LockForDelivery(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockForDelivery", reflect.TypeOf((*MockITaskRepo)(nil).LockForDelivery), ctx, id)
}

// MarkFailed mocks base method.
func (m *MockITaskRepo) MarkFailed(ctx context.Context, id int64, httpStatus int, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, httpStatus, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockITaskRepoMockRecorder) MarkFailed(ctx, id, httpStatus, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockITaskRepo)(nil).MarkFailed), ctx, id, httpStatus, lastError)
}

// MarkRetrying mocks base method.
func (m *MockITaskRepo) MarkRetrying(ctx context.Context, id int64, retryCount int, nextRetryTime time.Time, httpStatus int, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRetrying", ctx, id, retryCount, nextRetryTime, httpStatus, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRetrying indicates an expected call of MarkRetrying.
func (mr *MockITaskRepoMockRecorder) MarkRetrying(ctx, id, retryCount, nextRetryTime, httpStatus, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRetrying", reflect.TypeOf((*MockITaskRepo)(nil).MarkRetrying), ctx, id, retryCount, nextRetryTime, httpStatus, lastError)
}

// RecoverStuckTasks mocks base method.
func (m *MockITaskRepo) RecoverStuckTasks(ctx context.Context, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecoverStuckTasks", ctx, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecoverStuckTasks indicates an expected call of RecoverStuckTasks.
func (mr *MockITaskRepoMockRecorder) RecoverStuckTasks(ctx, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecoverStuckTasks", reflect.TypeOf((*MockITaskRepo)(nil).RecoverStuckTasks), ctx, timeout)
}

// ResetToRetry mocks base method.
func (m *MockITaskRepo) ResetToRetry(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetToRetry", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetToRetry indicates an expected call of ResetToRetry.
func (mr *MockITaskRepoMockRecorder) ResetToRetry(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetToRetry", reflect.TypeOf((*MockITaskRepo)(nil).ResetToRetry), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockITaskRepo) UpdateStatus(ctx context.Context, id int64, status string, httpStatus int, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, httpStatus, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockITaskRepoMockRecorder) UpdateStatus(ctx, id, status, httpStatus, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockITaskRepo)(nil).UpdateStatus), ctx, id, status, httpStatus, lastError)
}
